### ISSUE TITLE
Ambiguous/confusing project name

### ISSUE THREAD

**Issue by shimmythejj** [PhineasFreak/RSSVE#1]
since the existing RVE project...

> http://forum.kerbalspaceprogram.com/index.php?/topic/75157-wip105-rss-visual-enhancements-rve/
> https://github.com/Pingopete/RVE-KSP-1.0.4

...stands for "RSS Visual Enhancements", naming _this_ project "RSSVE" has lead to some confusion.

Could this project possibly be renamed to have a more unique an identifying name prone to less confusion in the future?

**Comment by PhineasFreak** [comment]
As i mentioned on the forums, RSSVE is not a replacement for RVE but more like an interim solution and it will be taken down when @Pingopete releases an update compatible with the latest version of KSP.
