### ISSUE TITLE
The atmosphere is flickering

### ISSUE THREAD

**Issue by Tcerbulis15** [PhineasFreak/RSSVE#12]
Hello, for some reason the atmosphere starts flickering when launching a vessel at around 160 000m. Any idea on how to resolve this issue? I'm using the new 1.3.1 version and EVE and Scatterer versions check out.

**Comment by PhineasFreak** [comment]
Flickering means that RSS is not working. Do you have any logs to provide?

**Comment by Tcerbulis15** [comment]
Like the actual RSS mod?

**Comment by PhineasFreak** [comment]
I have detailed information for that in the [RSSVE wiki pages](https://github.com/PhineasFreak/RSSVE/wiki).

**Comment by Tcerbulis15** [comment]
Ok thanks

**Comment by Tcerbulis15** [comment]
Hi, I can't send you the logs because they're too big

**Comment by Tcerbulis15** [comment]
If I look up when approaching 150000m alt then the flickering doesn't start. And the flickering doesn't happen when switching to a vessel from the space center. Any ideas on how to fix it?

**Comment by Tcerbulis15** [comment]
Ok. The problem somehow stopped lol. Thanks for the help!
