### ISSUE TITLE
Textures + Atmospheres messed up

### ISSUE THREAD

**Issue by njbrown09** [PhineasFreak/RSSVE#13]
Im running stock RSS + RSSVE (and all dependencies on 1.4.2)

https://gyazo.com/1625c8bc7c6830a2cef012f3faddc609
https://gyazo.com/6095be22ac802b1a63d9c2d6d5e7b733
https://gyazo.com/eda43749a0493becbec861f9b9f176a6

**Comment by PhineasFreak** [comment]
Congratulations, you completely ignored the readme clearly stating that:

# [RSSVE is compatible with Kerbal Space Program version 1.3.1. Older or newer versions are not supported.](https://github.com/PhineasFreak/RSSVE/wiki)

Have a nice day.

**Comment by njbrown09** [comment]
My bad. i meant 1.3.1 insead of 1.4.2.
