### ISSUE TITLE
Earth Apearing transparent for a brief moment

### ISSUE THREAD

**Issue by PedroCRb** [PhineasFreak/RSSVE#15]
I am currently using RSSVE 1.3.1-5 with scatterer 0.320b (0.324 keeps making the effects disapear at low orbital altitudes, just like showed [here](https://www.youtube.com/watch?v=lvqpIh91re4&feature=youtu.be))

I am experiencing two minor bugs:

1: When my spaceship is in the launch pad, and I zoom out as far as I can, the scatterer effects disapear. This seems to have something to do with that rendering cube bug, but I have no Idea how to fix it:

![screenshot_22](https://user-images.githubusercontent.com/41041790/42492918-e35f6308-83e8-11e8-9cc3-7a005fc7ca84.png)

![screenshot_23](https://user-images.githubusercontent.com/41041790/42492928-ee3ec4b2-83e8-11e8-9c15-9be590fe66db.png)

2: When passing trough the 100km mark, the earth becomes transparent and you can see the skybox behind it:

![screenshot_26](https://user-images.githubusercontent.com/41041790/42492995-1cf894ae-83e9-11e8-87c2-3496b2fc9b4a.png)

You can also see it when the vehicle is in the launch pad

![screenshot_24](https://user-images.githubusercontent.com/41041790/42493003-2ab99db8-83e9-11e8-96e9-90333f8e23c2.png)

**Comment by PhineasFreak** [comment]
Nothing i can do, these are Scatterer issues and they are also known/documented.
