### ISSUE TITLE
Aurora brightness way too high

### ISSUE THREAD

**Issue by WazWaz** [PhineasFreak/RSSVE#17]
The _MinLight of Auroras is 100. It should be something closer to 1.0 with EVE versions after about 1.3.

**Comment by PhineasFreak** [comment]
Thank you for the note. I saw that while doing some limited testing for KSP 1.4.5 but i thought that i broke something myself in the process.

I will fix it as part of the KSP 1.4 branch but i wil not give any promises: scatterer is still broken (at least for low orbital heights) and have not seen any general progress in the past few months.

**Comment by Sepax** [comment]
Which cfg did you change? Can’t find it.

**Comment by jrodrigv** [comment]
@PhineasFreak I have tested this locally and it works perfect. It is just cfg value change. Do you need a PR for it?

**Comment by PhineasFreak** [comment]
@jrodrigv I have fixed it but i have yet to push it in the repository since i am not expecting a release compatible with KSP 1.4/1,5 any time soon.

**Comment by jrodrigv** [comment]
@PhineasFreak  Which is the current stopper for doing a release?

**Comment by PhineasFreak** [comment]
Broken Scatterer release for KSP 1.4/no Scatterer release for KSP 1.5/no RSS for KSP 1.5\other KSP-unrelated issues.

To name a few...

**Comment by jrodrigv** [comment]
What do you mean with broken release of Scatterer for KSP 1.4?

I know there is no official releases but to be honest I have RSSVE "working" in KSP 1.4.5 and in KSP 1.5.1.
I have recompiled every single RSSVE dependency manually for KSP 1.5.1

Actually for Scatterer I have recompiled the Dev branch because is seems LGhassen has started to work again on it during October)

**Comment by jrodrigv** [comment]
I have recorded this video of RSSVE working in  KSP 1.5.1.

https://www.youtube.com/watch?v=lksUzoDYYCk&feature=youtu.be

Currently two big issues in my opinion are:
- Atmosphere lack between 140km and 230 km
- Volumetrics performance hit

**Comment by PhineasFreak** [comment]
> What do you mean with broken release of Scatterer for KSP 1.4?

> *Atmosphere is not properly drawn between 140km and 230 km not sure if this is an issue in RSSVE

>     * Atmosphere lack between 140km and 230 km

Here we go again:

* https://github.com/LGhassen/Scatterer/issues/32
* https://github.com/LGhassen/Scatterer/issues/43

>     * Volumetrics performance hit

Unless i am missing something, the RSSVE wiki covers that point extensively, including ways to mitigate that. Else, you can bug Waz to refactor the way that EVE creates the volumetric clouds.

Remember that all planet graphics mods are basically wrappers around EVE/Kopernicus/Scatterer.

**Comment by jrodrigv** [comment]
Thank you for the info!
