### ISSUE TITLE
Hard transition in atmospheric effects

### ISSUE THREAD

**Issue by Tonas1997** [PhineasFreak/RSSVE#18]
Not sure if this is the issue mentioned in the wiki's "known issues" page or something entirely different.

Basically, there's a height interval in which scatterer's atmospheric effects aren't rendered. While clouds do render without problem (as seen in the provided screenshots) the Earth's surface appears as dark-blue, as it would without any visual mods.

Inside the atmosphere.
![screenshot46](https://user-images.githubusercontent.com/43859708/46921143-6b5a1800-cfef-11e8-9fb4-c07474fc9417.png)

Once the vessel goes past 140km, atmospheric scatterer stops rendering.
![screenshot47](https://user-images.githubusercontent.com/43859708/46921146-714ff900-cfef-11e8-9bf8-d39f22b58b7d.png)

At around 230km, the visual effects start rendering again, "sweeping" across the screen.
![screenshot50](https://user-images.githubusercontent.com/43859708/46921149-7614ad00-cfef-11e8-807c-0e9ba1539c94.png)

The atmosphere is properly rendered again.
![screenshot51](https://user-images.githubusercontent.com/43859708/46921163-b96f1b80-cfef-11e8-9ede-ea2e23c7c886.png)

The effect can also be replicated in the tracking station by adjusting the camera perspective:
![screenshot61](https://user-images.githubusercontent.com/43859708/46921178-e6233300-cfef-11e8-98cf-924e11bb64fc.png)
![screenshot62](https://user-images.githubusercontent.com/43859708/46921181-e9b6ba00-cfef-11e8-94ba-1bd7b9ebe4c1.png)

**Comment by PhineasFreak** [comment]
Read the installation instructions, especially the "Mod Version List". Then check to see if your Scatterer version is 0.0324 instead of the proper 0.0320b.

**Comment by PhineasFreak** [comment]
[There is a better way to search for a KSP mod.](http://lmgtfy.com/?q=ksp+scatterer)
