### ISSUE TITLE
Earth looks like the sun once you reach orbit

### ISSUE THREAD

**Issue by Rex1812** [PhineasFreak/RSSVE#21]
I am running KSP 1.3.1 RSS/RP1 RSSVE v0.320b - other than taking over 5 mins to load and the surface of mars being friction-less it runs well and looks stunning ( esp.. launches through the clouds at sunrise); however, as soon as any craft reaches 140km (orbit) the sun side of earth looks like the sun (large gold ball) even from the moon.  Doses anyone have any idea how to fix this?
[ Intel Core i7 8700K - 32GB  - NVIDIA GeForce GTX 1080 Ti -500GB Solid State Drive(s)]

**Comment by Rex1812** [comment]
Hi Is this enough information? -any help much you can provide would much appreciated 
BW J.
Log
   
[KSP.log](https://github.com/PhineasFreak/RSSVE/files/2661227/KSP.log)

mod list ( this is my basic installation without KCT etc...)


[Mod list.txt](https://github.com/PhineasFreak/RSSVE/files/2661230/Mod.list.txt)

screen shot- it can also look gold/sun like when completely sun side

![polar1](https://user-images.githubusercontent.com/27972047/49705746-38469600-fbe6-11e8-9773-a9faeb61888b.jpg)

**Comment by Rex1812** [comment]
![man1](https://user-images.githubusercontent.com/27972047/49705797-b4d97480-fbe6-11e8-91ba-81cee9526774.jpg)

**Comment by Rex1812** [comment]
I have re-installed from scratch mod by mod and left out anything that might conflict - I have found a partial solution by editing the RSSVE_Kopernicus_Config.cfg as nothing else I could find referres  to 1400000 ~ this turn off the effect / breaks the mod-not in tracking. This leads me to wonder if I am using the correct Kopernicus version 1.3.1.7. I don't use ckan for KSP RSS.


@Body[Kerbin]
            @fadeStart = 100000
            @fadeEnd = 105000
            @deactivateAltitude = 14000000000 (changed from 1400000)

**Comment by PhineasFreak** [comment]
What happens if you remove the section completely? I am asking because the next version will not touch these parameters anymore.

**Comment by PhineasFreak** [comment]
It should not since it has nothing to do with any kind of "atmosphere" or "physics".
