### ISSUE TITLE
Fuzzy Water: Scatterer issue in v1.2.2, probably

### ISSUE THREAD

**Issue by Richard-Payne** [PhineasFreak/RSSVE#22]
Certain bits of water look like the static fuzz on an analogue TV.  See the attached screenshot, look at the Nile and the coast of Israel.  The image is obviously stationary but in the game, the fuzzy bits move like real TV static.

Ignore the horizontal bar across the screen.  This is an artifact of the screenshot program and is not present in the game

![screenshot from 2018-12-22 12-40-02](https://user-images.githubusercontent.com/6730730/50374602-82694780-05e8-11e9-9113-7785aedc4141.png)

I have the following in my gamedata directory.  I've included the versions for RSSVE and scatterer.  If you think any of the others are relevant then let me know and I'll look up the versions for those too.

AJE                      
B9_Aerospace_ProceduralWings         
B9PartSwitch                      
CommunityResourcePack              
CommunityTechTree         
ConnectedLivingSpace        
DeadlyReentry             
DistantObject
EngineGroupController   
EngineLight                         
EnvironmentalVisualEnhancements   
FerramAerospaceResearch            
Firespitter               
FShangarExtender            
KerbalEngineer            
KerbalJointReinforcement
Kopernicus               
KSCSwitcher                          
MechJeb2                          
ModularFlightIntegrator            
ModuleManager.2.7.5.dll   
ModuleManager.ConfigCache   
ModuleManager.ConfigSHA   
ModuleManager.Physics
ModuleManager.TechTree   
NavBallDockingAlignmentIndicatorCE   
NearFutureConstruction            
NearFutureElectrical               
NearFutureProps           
NearFuturePropulsion        
NearFutureSolar           
NearFutureSpacecraft
PersistentRotation       
PlanetShine                          
ProceduralFairings                
ProceduralFairings-ForEverything   
ProceduralParts           
RCSBuildAid                 
RealChute                 
RealFuels
RealHeat                 
RealismOverhaul                      
RealPlume                         
RealSolarSystem                    
RemoteTech                
RSSDateTime                 
RSS-Textures              
RSSVE v1.2.2-RC4
RW Saturatable
scatterer  v0.0320                 
ScienceRelay                      
SmokeScreen                        
SolverEngines             
TacFuelBalancer           
TestFlight
TextureReplacer
TriggerTech                         
[x] Science!

**Comment by Richard-Payne** [comment]
Oh, and I have the RSSVE_Scatterer_PlanetFix_Config.cfg fix enabled for the featureless sphere bug.

**Comment by PhineasFreak** [comment]
These are probably the city lights. Sometimes they render on top of everything else.

You can try two things:

* Disabling them in the "city_lights.cfg" file (under the "RSSVE/CityLights" directory)
* Checking if it happens on newer versions (as i do not support anything below KSP 1.3.1 anymore)

For the first step, your file should look like this after the node removal:

```
EVE_CITY_LIGHTS
{
}
```

**Comment by Richard-Payne** [comment]
Unfortunately I don't have 1.3.1.  I have v1.2.2 and can get 1.5.1, which RO doesn't support.
