### ISSUE TITLE
Northern hemisphere missing city lights 

### ISSUE THREAD

**Issue by MaxVielma** [PhineasFreak/RSSVE#24]
RSSVE-HR v1.3.1-6 & 5 seem like their northern region city lights are not working properly, cutting off above the US-Canada border and above the Mediterranean all the way accross Russia/Siberia. I was digging through the dds files in the Main Texture folder and saw that the game is failing to render the north pole file "EarthCitiesYn". I also noticed that the Arctic Ocean water texture is also failing to appear so its possibly related, but maybe not. I'm gonna try a few things to edit the dds file to see what I can do but, just in case anyone else has bothered you about his, at least now you can say it's being addressed 😜

**Comment by MaxVielma** [comment]
Yeah that was me, or at least one post was. Bornholio sent me here. I originally thought the Y+ and Y- cube maps were mostly blank but I just wasn't looking hard enough.

**Comment by MaxVielma** [comment]
Looks like flipping it 180 degrees is what it needed. However its still rendering this way: 
![screenshot 83](https://user-images.githubusercontent.com/47956984/53385427-f820c500-3943-11e9-867a-8ab5071e7dc2.png)
![screenshot 84](https://user-images.githubusercontent.com/47956984/53385438-066ee100-3944-11e9-8e45-1d902a239c2e.png)
![screenshot 85](https://user-images.githubusercontent.com/47956984/53385448-0bcc2b80-3944-11e9-9fac-39d387594213.png)

**Comment by MaxVielma** [comment]
Getting some where. Still a tad weak in some spots but not too bad.
![screenshot 91](https://user-images.githubusercontent.com/47956984/53388564-56a07000-3951-11e9-94b2-3365bab1a67e.png)
![screenshot 90](https://user-images.githubusercontent.com/47956984/53388575-3f618280-3951-11e9-83de-cd84c0040923.png)
![screenshot 89](https://user-images.githubusercontent.com/47956984/53388578-42f50980-3951-11e9-9e33-f727f2a9658f.png)
![screenshot 86](https://user-images.githubusercontent.com/47956984/53388581-47212700-3951-11e9-98ce-f3492d86bbf5.png)

**Comment by MaxVielma** [comment]
[EarthCitiesYn.zip](https://github.com/PhineasFreak/RSSVE/files/2903857/EarthCitiesYn.zip)

**Comment by PhineasFreak** [comment]
Should be now fixed in the KSP 1.6.1 dev branch.
