### ISSUE TITLE
Trying to Add Volumetric Clouds to Jupiter With No Success

### ISSUE THREAD

**Issue by CtrlAltElitist** [PhineasFreak/RSSVE#3]
I have the clouds.cfg set up to have volumetric clouds on Jupiter, yet none show up as i pass through the cloud layers' set altitude. Is there more to the volumetric clouds than the clouds.cfg?
Heres my configuration for jupiter as it currently stands:

	OBJECT
	{
		name = JupiterAtmosphere
		body = Jupiter
		altitude = 320000
		detailSpeed = 0,4,0
		killBodyRotation = True
		settings
		{
			_UVNoiseTex = RSSVE/Clouds/Textures/Particle/UVNoise
			_UVNoiseScale = 0.000325
			_UVNoiseStrength = 0.000045
			_UVNoiseAnimation = 0.5,0.25
			_DetailScale = 150
			_Color = 200,200,180,80
			_DetailDist = 0.0000001
			_DistFade = 0.0001
			_DistFadeVert = 0.00001
			_MainTex = RSSVE/Clouds/Textures/Atmosphere
			_DetailTex = RSSVE/Clouds/Textures/DetailVenus
			}
		}
		layer2D
		{
			macroCloudMaterial
			{
				_RimDistSub = 1
				_InvFade = 0.005
				_RimDist = 0.00001
				_FalloffScale = 10
				_MinLight = 1
				_FalloffPow = 5
			}
			shadowMaterial
			{
				_ShadowFactor = 0.4
			}
		}
		layerVolume
		{
			size = 8000,2
			area = 80000,4
			noiseScale = 64,64,64
			rotationSpeed = 0.0001
			followDetail = True
			particleMaterial
			{
				_MinScatter = 5
				_Opacity = 1
				_InvFade = 0.00001
				_Tex = RSSVE/Clouds/Textures/Particle/CloudParticle
			}
		}
	}
	OBJECT
	{
		name = JupiterCloudsLow
		body = Jupiter
		speed = 0,6250,0
		detailSpeed = 0,4,0
		altitude = 340000
		killBodyRotation = True
		settings
		{
			_MainTex = RSSVE/Clouds/Textures/JupiterCloudsLow
			_DetailTex = RSSVE/Clouds/Textures/DetailVenus
			_DetailScale = 150
			_DetailDist = 0.0000001
			_DistFadeVert = 0.00001
			_DistFade = 0.0001
			_Color = 200,200,180,512
			_UVNoiseTex = RSSVE/Clouds/Textures/Particle/UVNoise
			_UVNoiseScale = 0.000325
			_UVNoiseStrength = 0.000045
			_UVNoiseAnimation = 0.5,0.25
		}
		layer2D
		{
			macroCloudMaterial
			{
				_FalloffScale = 10
				_MinLight = 1
				_RimDistSub = 1
				_RimDist = 0.00001
				_InvFade = 0.005
				_FalloffPow = 5
			}
			shadowMaterial
			{
				_ShadowFactor = 0.4
			}
		}
		layerVolume
		{
			size = 8000,2
			area = 80000,4
			rotationSpeed = 0.0001
			noiseScale = 64,64,64
			followDetail = True
			particleMaterial
			{
				_MinScatter = 5
				_Opacity = 1
				_InvFade = 0.00001
				_Tex = RSSVE/Clouds/Textures/Particle/CloudParticle
			}
		}
	}
	OBJECT
	{
		name = JupiterCloudsMid
		body = Jupiter
		altitude = 360000
		speed = 0,6250,0
		detailSpeed = 0,4,0
		offset = 0,180,0
		killBodyRotation = True
		settings
		{
			_MainTex = RSSVE/Clouds/Textures/JupiterCloudsLow
			_DetailTex = RSSVE/Clouds/Textures/DetailVenus
			_DetailScale = 150
			_Color = 200,200,180,512
			_DistFade = 0.0001
			_DetailDist = 0.0000001
			_DistFadeVert = 0.00001
			_UVNoiseTex = RSSVE/Clouds/Textures/Particle/UVNoise
			_UVNoiseScale = 0.000325
			_UVNoiseStrength = 0.000045
			_UVNoiseAnimation = 0.5,0.25
		}
		layer2D
		{
			macroCloudMaterial
			{
				_FalloffScale = 10
				_MinLight = 1
				_RimDistSub = 1
				_InvFade = 0.005
				_FalloffPow = 5
				_RimDist = 0.00001
			}
			shadowMaterial
			{
				_ShadowFactor = 0.4
			}
		}
		layerVolume
		{
			size = 8000,2
			area = 80000,4
			rotationSpeed = 0.0001
			noiseScale = 64,64,64
			particleMaterial
			{
				_MinScatter = 5
				_Opacity = 100
				_InvFade = 0.00001
				_Tex = RSSVE/Clouds/Textures/Particle/CloudParticle
			}
		}
	}
	OBJECT
	{
		name = JupiterBandsLow
		body = Jupiter
		altitude = 380000
		speed = 0,-6250,0
		detailSpeed = 0,4,0
		killBodyRotation = True
		settings
		{
			_MainTex = RSSVE/Clouds/Textures/JupiterBandsLow
			_DetailTex = RSSVE/Clouds/Textures/DetailVenus
			_DetailScale = 150
			_Color = 180,130,75,512
			_DetailDist = 0.0000001
			_DistFade = 0.0001
			_DistFadeVert = 0.00001
			_UVNoiseTex = RSSVE/Clouds/Textures/Particle/UVNoise
			_UVNoiseScale = 0.000325
			_UVNoiseStrength = 0.000045
			_UVNoiseAnimation = 0.5,0.25
		}
		layer2D
		{
			macroCloudMaterial
			{
				_FalloffScale = 10
				_MinLight = 1
				_RimDistSub = 1
				_RimDist = 0.00001
				_InvFade = 0.005
				_FalloffPow = 5
			}
			shadowMaterial
			{
				_ShadowFactor = 0.4
			}
		}
		layerVolume
		{
			size = 8000,2
			area = 80000,4
			rotationSpeed = 0.0001
			noiseScale = 64,64,64
			particleMaterial
			{
				_MinScatter = 5
				_Opacity = 1
				_InvFade = 0.00001
				_Tex = RSSVE/Clouds/Textures/Particle/CloudParticle
			}
		}
	}
	OBJECT
	{
		name = JupiterBandsHigh
		body = Jupiter
		altitude = 400000
		speed = 0,25000,0
		detailSpeed = 0,4,0
		killBodyRotation = True
		settings
		{
			_MainTex = RSSVE/Clouds/Textures/JupiterBandsHigh
			_DetailTex = RSSVE/Clouds/Textures/DetailVenus
			_DetailScale = 150
			_Color = 230,220,220,512
			_DetailDist = 0.0000001
			_DistFade = 0.0001
			_DistFadeVert = 0.00001
			_UVNoiseTex = RSSVE/Clouds/Textures/Particle/UVNoise
			_UVNoiseScale = 0.000325
			_UVNoiseStrength = 0.000045
			_UVNoiseAnimation = 0.5,0.25
		}
		layer2D
		{
			macroCloudMaterial
			{
				_RimDistSub = 1
				_FalloffScale = 10
				_MinLight = 1
				_RimDist = 0.00001
				_InvFade = 0.005
				_FalloffPow = 5
			}
			shadowMaterial
			{
				_ShadowFactor = 0.4
			}
		}
		layerVolume
		{
			size = 8000,2
			area = 80000,4
			rotationSpeed = 0.0001
			noiseScale = 64,64,64
			followDetail = True
			particleMaterial
			{
				_InvFade = 0.00001
				_Opacity = 100
				_MinScatter = 5
				_Tex = RSSVE/Clouds/Textures/Particle/CloudParticle
			}
		}
	}
Am I simply missing something? Or are the Volumetric Clouds configured in some other way?

**Comment by PhineasFreak** [comment]
The opacity of the volumetric particles is tied to the opacity of the cloud layer texture (alpha channel of the _Color parameter) but as i see you have already taken care of that. Apart from that it should work.

Give me some time to check if there is actually an issue with the default configs. Please note that if you have added them manually (i.e. not via the EVE GUI) then make sure that the changes are valid.

**Note for future reference:** the Jupiter layers have been refactored so some of these might not work after the 1.2.1 update. Volumetrics for all bodies are also planned in a future release.

**Comment by CtrlAltElitist** [comment]
I don't plan on updating to 1.2.1 I spent way too much time setting this up for 1.1.3. I had to overwrite scatterers default .half files for Venus by copying them and pasting them in the scatterer atmosphere folder manually. I've set venus's Clouds to the same settings as Jupiter and they work just fine, even following the high speeds of the detail texture. Hell I got dirt clouds on the moon. But not on the one place that definitely has clouds. Does altitude limit the appearance of volumetrics? That's the last thing I could think of that could cause the clouds to not be visible. Changing the alpha channel of the textures also over saturates the appearance of jupiter when viewed at a distance, while still not fixing the volumetrics. I will keep tinkering with it, let me know if you can find anything keeping jupiter from behaving. I appreciate all of your feedback, and your work is fantastic.

**Comment by PhineasFreak** [comment]
> I had to overwrite scatterers default .half files for Venus by copying them and pasting them in the scatterer atmosphere folder manually.

Debugging question: how's that? I mean, why it did not work in the first place?

Try playing around with the following parameters:

* -DistFade
* -DistFadeVert

These control the distance from the camera that the volumetrics are rendered. Also, the parameter "visibleRange" under the "layerVolume" also controls the loading/unloading of the particles. The default value is only 10 km, meaning that you have to get really close for them to show up.

I also did a quick test (with both the old and the new Jupiter EVE configs) and i got them to show up only when i was just above the actual cloud layer altitude.

**Comment by CtrlAltElitist** [comment]
I will give it a shot. fingers crossed. *Initiates 15 minute game startup*a

Also is there a way to get up close to the clouds without me having to fly a mission there?

**Comment by CtrlAltElitist** [comment]
It still did not work, so I decided to do a fresh install of scatterer, EVE, and RSSVE to see if it was due to outdated configs for either of the two.

**Comment by PhineasFreak** [comment]
You can also use the "develop" branch with the latest KSP 1.1.3 version of Scatterer (0.0255), they are compatible. I have added volumetrics to Jupiter (to use as a starting point), although it is really difficult to test and debug them.
