### ISSUE TITLE
I can't see Earth view clicking "M"  [RSSVE v1.2.2-RC3]

### ISSUE THREAD

**Issue by jrodrigv** [PhineasFreak/RSSVE#6]
Maybe this is a know issue or something done deliberately. But After updating from RC2 to RC3  I can't use the Map view anymore.

I hope this can be fixed for the final release because in my opinion to not have this view is not an option.

**Comment by PhineasFreak** [comment]
There are some users that have reported that but i have not been able to reproduce it. The workaround for now is to copy the Kerbin Scatterer config (from the basic Scatterer installation) and overwrite the Earth one.

**Comment by PhineasFreak** [comment]
The cause of this bug was finally traced to the DirectX11 and/or OpenGL command line switches (in addition to an unknown change from my part) under Windows.

**Comment by PhineasFreak** [comment]
I have implemented a temporary patch to fix it. You can get it from [**here**](https://raw.githubusercontent.com/PhineasFreak/DocBin/master/DocBin/generic_files/RSSVE_Scatterer_PlanetFix_Config.cfg) (right - click the page and save it - it will prompt you to save it as a **.cfg** file)

**Comment by jrodrigv** [comment]
Thanks. I will tested it during this week.
