### ISSUE TITLE
Exception Unhandeled.

### ISSUE THREAD

**Issue by MMattera21** [PhineasFreak/RSSVE#7]
I have all dependencies installed correctly and up to date.
Here is what my output_log.txt says about RSSVE.
https://hastebin.com/asideqohez.sql

**Comment by PhineasFreak** [comment]
I will need at least the complete KSP or output log files.

**Comment by MMattera21** [comment]
Ok i'm running it one more time just to make sure i might have fixed if not i'll post back in like ~10 minutes from now.

**Comment by MMattera21** [comment]
Here is a list of my addons. Most of them are CKAN downloaded and enabled. To be honest with you I think CKAN is causing this, it usually does 90% of the time.

Sorry i can't upload the text from the output_log.txt into a haste or pastebin so i'm gonna upload it to a hosting site.

Sorry Mega and MediaFire were a pain. Here's a zippshare link: http://www96.zippyshare.com/v/pEowNgUw/file.html

**Comment by PhineasFreak** [comment]
And you are right. I do not support CKAN installations because when you install EVE via CKAN it also installs the EVE configs and textures (the "**BoulderCo**" folder under your GameData folder).

Remove the folder and everything should be OK.

**Comment by MMattera21** [comment]
OK i downloaded your mod from the official github page i deleted the boulderco and i'll make sure Ckan recognizes that and i'll give this a spin right now.

**Comment by MMattera21** [comment]
To clarify i need the forked version of EVE correct?

**Comment by PhineasFreak** [comment]
Yes. The respective links are listed in the RSSVE Wiki Installation page.

**Comment by PhineasFreak** [comment]
OK, from your log file i can see that something is broken:

```
ADDON BINDER: Cannot resolve assembly: KSPUtil, Culture=neutral, PublicKeyToken=null
```

And:

```
AssemblyLoader: Exception loading 'Atmosphere': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0

Non platform assembly: D:\Steam\steamapps\common\Kerbal Space Program\GameData\EnvironmentalVisualEnhancements\Plugins\CelestialShadows.dll (this message is harmless)
AssemblyLoader: Exception loading 'CelestialShadows': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0 
```

Make sure that your base KSP installation is up to date. There are possibly leftover files from the previous KSP 1.1.3 version.

**Comment by MMattera21** [comment]
Yeah you're right these types of configs like to break game installs and fragment things ill run a steam verify integrity as well, thanks for taking time for helping me. :D

**Comment by Olympic1** [comment]
> I do not support CKAN installations because when you install EVE via CKAN it also installs the EVE configs and textures (the "BoulderCo" folder under your GameData folder).

Simple to solve that by adding RSSVE to ckan, we just need a full release. There is a [PR](https://github.com/KSP-CKAN/NetKAN/pull/5321) waiting for merge.

**Comment by MMattera21** [comment]
EVE isn't being recognized as an addon in game??????
http://imgur.com/a/GSGQi

**Comment by MMattera21** [comment]
I don't even know. I'm done with CKAN gonna nuke my whole game installation, reinstall, then just do manual installs.

**Comment by PhineasFreak** [comment]
I would suggest to:

* Delete the Steam KSP folder completely.
* Re-download a fresh KSP distribution
* Copy the KSP folder somewhere outside the Steam (and Program Files) folder(s)
* Install your mods via CKAN (but not the RSSVE dependencies)
* Install RSSVE and it's dependecies manually

**Comment by MMattera21** [comment]
Ok will do.

**Comment by PhineasFreak** [comment]
@Olympic1 Sorry but i did not see your response. As long as RSSVE is in a pre-release state there is no way to add it to CKAN. I am hoping that it will not take long to move to a normal release but there are still bugs to fix.

**Comment by MMattera21** [comment]
I'm so lost, i think i'm doing everything right, now AVC says EVE isn't even loaded. What do you think would cause that?

**Comment by MMattera21** [comment]
http://imgur.com/a/nAVrQ

http://www31.zippyshare.com/v/CfODkTpO/file.html

At this point CKAN can suck it.

**Comment by MMattera21** [comment]
Your mod doesn't even show up in the AVC either when the game is patching.

**Comment by MMattera21** [comment]
Meh, this will probably get fixed later. Your mod and EVE aren't even loading in the game even though they're installed properly. Probably just incompatibility which sucks thank you for your great help though. Guess i'll have to play stock KSP.  😞

**Comment by Olympic1** [comment]
@MMattera21 try removing DDSloader, it seems to cause issues. KSP can now load .dds files without that mod too.

**Comment by PhineasFreak** [comment]
@MMattera21 More errors:

```
MissingMethodException: Method not found: 'KSPUtil.PrintDate'.
```

Also, DDSLoader has been deprecated since...forever:

```
MissingMethodException: Method not found: 'GameDatabase.TextureInfo..ctor'.
  at DDSLoader.DatabaseLoaderTexture_DDS+<Load>c__Iterator0.MoveNext () [0x00000] in <filename unknown>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 
UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
<LoadObjects>c__Iterator4A:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

Your log is literally full of these errors (not surprising though). Basically, none of the textures are ever loaded by KSP:

```
Load(Texture): RSSVE/Assets/DetailTextures/DetailAltostratus
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

MissingMethodException: Method not found: 'GameDatabase.TextureInfo..ctor'.
  at DDSLoader.DatabaseLoaderTexture_DDS+<Load>c__Iterator0.MoveNext () [0x00000] in <filename unknown>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0 
UnityEngine.MonoBehaviour:StartCoroutine_Auto(IEnumerator)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
<LoadObjects>c__Iterator4A:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

```

BTW you are missing the, required by Real Solar System, RSS-Textures folder. You cannot expect RSS to even load without these textures.

Seeing that the installation path did not change and that the KSPUtil errors continue to exist should i assume that a clean install was not done?

**Comment by MMattera21** [comment]
No i did the clean install, i'm just not installing it right, it's whatever though.

**Comment by MMattera21** [comment]
I think this may just be a problem with KSP-AVC not displaying the mod.
I just installed everything correctly and AVC doesn't detect anything not ckan installed. So my own ignorance is what cost caused this whole issue. Thanks for your help Phineas, this is an amazing mod you got. You can close this as solved.
